---
title: "Nightlight and Populations Temporal Analysis"
author: "Caitlin Buckle"
date: "2026-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

/**** Start of imports. If edited, may not auto-convert in the playground. ****/
var testarea = 
    /* color: #12ff1f */
    /* shown: false */
    /* displayProperties: [
      {
        "type": "rectangle"
      }
    ] */
    ee.Geometry.Polygon(
        [[[124.57250550401113, 36.88295454668949],
          [124.57250550401113, 33.28810419917295],
          [127.20922425401113, 33.28810419917295],
          [127.20922425401113, 36.88295454668949]]], null, false);
/***** End of imports. If edited, may not auto-convert in the playground. *****/


## MB5370 Module Four Workshop Three  


###  Nightlights in Global Coastlines Analysis 

#### Grid Analysis 

var grid = ee.FeatureCollection('users/murrnick/mb5370/worldgrid_5deg');

Map.addLayer(grid, {color: 'white'},'grid',false, 0.4); 

#### Import population data from GEE catalogue, and filter to images from 2000 and 2015 

var population = ee.ImageCollection("CIESIN/GPWv411/GPW_Population_Count");

print (population);

var pop_2000 = ee.Image("CIESIN/GPWv411/GPW_Population_Count/gpw_v4_population_count_rev11_2000_30_sec");

print(pop_2000);

var pop_2015 = ee.Image("CIESIN/GPWv411/GPW_Population_Count/gpw_v4_population_count_rev11_2015_30_sec");

print(pop_2015);

var pop_vis = {min:0.0, max:1000.0, palette: ['ffffe7','86a192','509791','307296','2c4484','000066'], 
};

#### Add population layers to map 

Map.addLayer(pop_2000, pop_vis, 'Population Count 2000'); 

Map.addLayer(pop_2015, pop_vis, 'Population Count 2015');

#### Import NOAA nightlight data from GEE data catalogue 

var nightlight = ee.ImageCollection("NOAA/DMSP-OLS/NIGHTTIME_LIGHTS");

print(nightlight);

#### Isolate nighlight images from 2000 and 2013

var nl_2000 = ee.Image("NOAA/DMSP-OLS/NIGHTTIME_LIGHTS/F142000");

var nl_2013 = ee.Image("NOAA/DMSP-OLS/NIGHTTIME_LIGHTS/F182013");

print(nl_2000);

print(nl_2013);

var nl_2000 = ee.Image("NOAA/DMSP-OLS/NIGHTTIME_LIGHTS/F142000").select(['avg_vis'],['nightlight']); // select and rename 

var nl_2013 = ee.Image("NOAA/DMSP-OLS/NIGHTTIME_LIGHTS/F182013").select(['avg.vis'],['nighlight']);

print ('nightlight 2000 processed', nl_2000);

print('nightlight 2013 processed', nl_2013); 

#### Add nightlight layers to map 

Map.addLayer(nl_2000,{palette:["0B192C", "1E3E62", "384B70", "5D4E6D", "FFB703","FFEE32"],min:5,max:60},'nl_2000',true,0.8);

Map.addLayer(nl_2013,{palette:["0B192C", "1E3E62", "384B70", "5D4E6D", "FFB703","FFEE32"],min:5, max:60},'nl_2013',true,0.8);

#### Import coastlines dataset and add to map 

var coast = ee.FeatureCollection('projects/UQ_intertidal/dataMasks/naturalEarthCoastline_v1');
Map.addLayer(coast,{color:'yellow'},'coast');

#### Using the previously defined grid, generate grids where mangrove ecosystems are likely to occur (using coastlines) dataset to reduce total area that GEE has to analyse 

var coastgrid = grid 
.filter(ee.Filter.bounds(coast))

// .filter(ee.Filter.bounds(testarea));// TEST AREA TO DELETE LATER (geometry - polygon) limits the size of the analysis, takes a long time to run full analysis so only do that at the end

Map.addLayer(coastgrid,{color:"0090fe"},'coastgrid'); // going to analyse human impact within these regions (likely to have mangroves) - removes areas where mangroves are not likely to occur at all

// created geometry (green box called 'testarea'), filtered coastgrids to only include 4 that are included in the box. 

#### Create variables for population/nightlight change from 2000 to 2015/2013 
var pop_change = pop_2015
  .subtract(pop_2000)
  .clip(coastgrid);
  
Map.addLayer(pop_change,{palette: ['darkblue','blue','lightblue'],min:-500, max:500},'pop_change',true, 0.9);

var nl_change = nl_2013
  .subtract(nl_2000)
  .clip(coastgrid);
  
Map.addLayer(nl_change,{palette: ['darkgreen','white','lightgreen'],min:-50,max:50},'nl_change',true,0.9);

#### Create variable for average change in nightlights per grid 

var nl_changePerCoastgrid = nl_change.reduceRegions({
  collection: coastgrid,
  reducer:ee.Reducer.mean(), 
  scale: 1000, // computing at a larger scale for speed 
});

print(nl_changePerCoastgrid.first()); // mean = 5.875

var pop_changePerCoastgrid = pop_change.reduceRegions({
  collection: coastgrid,
  reducer:ee.Reducer.mean(), 
  scale: 1000, // computing at a larger scale for speed 
});

Map.setCenter(127.7669, 35.9078, 3);

#### Global Analysis - Export the results (analyse in batch mode). Slower but allows your analyses to proceed by removing some of the limitations that are applied when running it interactively 

// Export the results to asset 
// Export.table.toAsset({
//   collection: pop_changePerCoastgrid, 
//   description: 'export_pop_toAsset',
//   assetId: 'pop_changePerCoastgrid'
// }); 

// Export.table.toAsset({
//   collection:nl_changePerCoastgrid,
//   description: 'export_nl_toAsset',
//   assetId: 'nl_changePerCoastgrid'
// }); 

## Results Generation 

#### Create a variable for population change per coast grid 

var pop_result = ee.FeatureCollection('projects/mb5370-first-project/assets/pop_changePerCoastgrid');

//Map.addLayer(pop_result);

print(pop_result);

var empty = ee.Image().byte() ;

var palette = ['green','yellow','orange,','red'];

var pop_changePerCoastgrid = empty.paint({
  featureCollection:pop_result,
  color:'mean'
});

var snazzy = require("users/aazuspan/snazzy:styles");

snazzy.addStyle("https://snazzymaps.com/style/48750/blank-map","Blank Map");

Map.addLayer(pop_changePerCoastgrid,{max:112,palette:['#0047AB','#1E63C3','#3B7FDB','#589BF2','#80C285','#B4D66E','#E5C048','#E98F3A','#D95336','#CC0000']},'Population Change Results', true,0.9);

#### Create a variable for nightlight change per coast grid 

var nl_result = ee.FeatureCollection('projects/mb5370-first-project/assets/nl_changePerCoastgrid');
//Map.addLayer(nl_result); 
print(nl_result); 

var empty2 = ee.Image().byte(); 

var palette = ['green','yellow','orange,','red'];

var nl_changePerCoastgrid = empty.paint({
  featureCollection:nl_result,
  color:'mean'
}); 

Map.addLayer(nl_changePerCoastgrid,{max:8,palette: ['#0047AB','#1E63C3','#3B7FDB','#589BF2','#80C285','#B4D66E','#E5C048','#E98F3A','#D95336','#CC0000']},'Nightlight Change Result',true,0.9); 

#### Set map centre to East China Coastline 
Map.setCenter(127.7669, 35.9078, 3);